import { Inter, Lato, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const playfair_display = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-playfair_display",
});

export const metadata = {
  title: "Nepal Law firm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter.className} ${playfair_display.variable}`}
      >
        <main className="w-full min-height-screen flex flex-col">
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
